### ISSUE TITLE
Link the max speed of the consist to the composition code in STDCM

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#10016]
# Description

> [!IMPORTANT]
> Updated after [this comment](https://github.com/OpenRailAssociation/osrd/pull/10039#discussion_r1887193308)

Leftover work from https://github.com/OpenRailAssociation/osrd/issues/9712

Composition codes can affect the max speed of a train. For freight trains, here is the mapping : 

| Code  | Max speed (km/h) |
|-------|------------------|
| HLP   | 100                 |
| MA80  | 80               |
| MA90  | 90               |
| MA100 | 100              |
| ME100 | 100              |
| ME120 | 120              |
| ME140 | 140              |
| ME160 | 160              |
| MVGV  |  200                |

# AC

- [ ] The table above has been implemented and changing the composition code update the max speed if the chosen code is supposed to lower it. User's input are still not overwritten.

**Comment by maelysLeratRosso** [comment]
This is the mapping I observe on staging 

| Code | vMax | Diff ? |
| -------|-------|----|
| HLP | **100** |  x |
| MA100 | 100 |  |
| MA80 | 80 |  |
| MA90 | 90 |  |
| ME100 | 100 |  |
| ME120 | 120 |  |
| ME140 | 140 |  |
| **MV160** | **-** | x |
| MVGV | **200** | x |

Which is not exactly the one from the table. Did it change @axrolld @Wadjetz ??

The differences are : 
- Value for HLP
- Value for MVGV
- For ME160 in the issue table, we have MV160 in the list in the app, and the value is None instead of 160

**Comment by axrolld** [comment]
My bad i forgot to update the issue main body after [this comment](https://github.com/OpenRailAssociation/osrd/pull/10039#discussion_r1887193308). I just did the fix. Good catch !

**Comment by maelysLeratRosso** [comment]
Now it's correct then :) And for the points 2 & 3 they seem corrected as well. I validate the ticket !
