### ISSUE TITLE
Recommendation for Repository as part of a university project

### ISSUE THREAD

**Issue by NickyDelgado69** [OpenRailAssociation/osrd#10015]
[SBB OSS Policy.docx](https://github.com/user-attachments/files/18085336/SBB.OSS.Policy.docx)
Good day,

As part of one of our university classes we are tasked with working on an impovement recommendation for an ongoing Open Source project.

For this project my recommendation consist of the following:
I think that it would be helpful to have a specific document to explain the policies the Open Railway Association defines for their project.
As I have collected the information for Open Source policies with regards to the SBB as part of the Open Railway Association I would like to add this document with a separate pull request.

Thank you granting the opportunity to do so.

Greetings,
@NickyDelgado69

**Comment by flomonster** [comment]
Hi @NickyDelgado69,

Thanks for your interest in the OpenRail Association. OSRD is one of the projects hosted by OpenRail.
The association have a specific repository ([technical-committee](https://github.com/OpenRailAssociation/technical-committee)) that contains documentation on their "policies".

I encourage you to discover this repository and feel free to open pull request to suggest improvements or additions.
I'm closing your issue since it's linked to the wrong repository. Feel free to comment if you still have questions.

I'll be happy to discuss your proposals in the technical committee's repository.

Have a nice day,
