### ISSUE TITLE
Front Edition: Write helper functions for linear metadata

### ISSUE THREAD

**Issue by jacomyal** [OpenRailAssociation/osrd#1168]
We need a tested function that keeps a linear metadata of a track (slope or curve) when its geography is updated. Basically, the goal is to preserve in the linear metadata curve everything before and after what is impacted by the geometry update.

**Comment by sim51** [comment]
This is what I did so far

- sync linear metadata with the geometry : do the impact on the LM when we add/move/delete point on the geometry
- helper functions on the ML (split, merge, resize fragment)

I still need to do : 
-  edges cases (extremities of the LineString) for the sync with the geo

**Comment by sim51** [comment]
Do we need a function to initialize a LM on a LineString where every segment has the same size ? 
Or with a define step size (except for the last one) ?  

For now I follow the LineString segments

**Comment by sim51** [comment]
remaining tasks : 

- [x] Avoid scroll on side panel when we hover a dataviz (otherwise user can't zoom in/out with the mouse)
- [x]  When a component is selected, do a custom onChange when a begin/end change has been done
- [x] Be able to drag on the dataviz
- [x] Be able to resize a segment with the mouse 
- [x] When go to prev/next selected, the selected segment should be visible on the dataviz (can be hidden in case of zoom)
