### ISSUE TITLE
Inaccurate train positions in the front-end

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#1365]
### Description
Position on map on specific time seems unaccurate: on specific stops: train is not exactly on the PR position. Investigate and solve.

**Comment by alexandredamiron** [comment]
- [ ] Train are exactly positioned on the PR they are supposed to be at correct times

**Comment by multun** [comment]
@flomonster We finally got what makes this bug happen. There are two lengths, the actual length, and the geometry length:
 - the path offsets are relative to the length attribute of track sections
 - the front-end interprets offsets relative to the length of the geometry

We should either:
 - give the length and geometry of track sections instead of the complete path, so the front-end can locate objects
 - provide the geometry and actual length of track sections, so the front-end can correct for the discrepancy

Alexandre and I favor the first option

**Comment by multun** [comment]
Closed in favor of https://github.com/DGEXSolutions/osrd/issues/1469
