### ISSUE TITLE
Mareco sometimes exhibits a logical contradiction

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#1535]
Mareco sometimes fails to find an intersection between the acceleration and slowdown times.
We should investigate why this happens and what the proper fix should be

See the hotfix discussion for a reproducer
https://github.com/DGEXSolutions/osrd/pull/1405#discussion_r928817082

**Comment by axrolld** [comment]
@eckter  the bug came from the fact that no `EnvelopeAttr` was given to `EnvelopeParts` coming from the Linear allowance.

So when MARECO algorithm was scanning the core envelope to find braking `EnvelopeParts`, some of them were not found as they were missing metadata.

To fix the bug, we just need to add EnvelopeProfile attribute here :

https://github.com/DGEXSolutions/osrd/blob/33b278b4ad4123607c62dc06a55a3f1b937b2551/core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/LinearAllowance.java#L47

And replace it with :

```java
var scaledPart = EnvelopePart.generateTimes(attributesOfTheInitialPart, positions, scaledSpeeds);
```

**Comment by axrolld** [comment]
Fixed by @eckter in https://github.com/DGEXSolutions/osrd/pull/1405
