### ISSUE TITLE
bug: front: when selecting a track, the cursor can snap to a track while selecting another

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#2365]
It can be very confusing because it often causes "no path found" error, and there's no visual indication of what actually happens.

See the video below for a better description (sorry about the small recording glitch).

https://user-images.githubusercontent.com/3882074/202489806-19da71fd-6248-445b-9cd5-bd73da20658a.mp4

**Comment by nicolaswurtz** [comment]
I think it's simply because the "point" sent is the position of the mouse cursor and not the circle stuck to the track which is here just as an indication.

The problem is that the blue and white circle is not necessarily displayed on the track closest to the cursor systematically because of the way it is done: to detect the closest point you have to pass a geometry to turf, so it is done in two steps:
- get the geometry of the line hovered in geojson
- pass it to turf with the position of the cursor to get the coordinates of the nearest line point

To change the line/geometry you have to fly over the other geometry to update the geojson. It's done quickly but not exactly. I don't really see any other way to do it, we will have to go through the extraction of the hovered data before looking for the closest point, and I think that's where the problem lies if several polylines intersect.

http://turfjs.org/docs/#nearestPointOnLine
