### ISSUE TITLE
Come up with a unified/standardized translation process + error formatting

### ISSUE THREAD

**Issue by anisometropie** [OpenRailAssociation/osrd#2697]
Description of the problem :

Currently, errors returned by backend services are not translated :

### Example in `api`

![Screenshot_20221222_124335](https://user-images.githubusercontent.com/24652545/209127311-a2cbdbd0-d893-4fbe-96e2-7929d4665c15.png)

This is what I get in the front :

![Screenshot_20221222_132429](https://user-images.githubusercontent.com/24652545/209134093-4f200530-66c0-4c95-a69e-3f579f0463b1.png)

When thrown, the raw data of the error is shown directly in the front.

![Screenshot_20221222_124614](https://user-images.githubusercontent.com/24652545/209127843-bd36e8d6-19c7-4742-8f0a-5d1c3baf1be6.png)

### Example, error sent directly from `core`

![Screenshot_20221222_132602](https://user-images.githubusercontent.com/24652545/209134280-b7212ed5-4b89-4216-bc80-7fbe2784a3e5.png)

![Screenshot_20221222_132243](https://user-images.githubusercontent.com/24652545/209133838-cade5665-598f-4b08-8a6e-00c33a4f4a95.png)

### Required fields in rest framework or django

Yet another format

![Screenshot_20221222_134021](https://user-images.githubusercontent.com/24652545/209136619-bade44e6-70e7-426d-8848-616833b0b9e8.png)

### To do

We need to have a process, a tool to translate informations displayed to the user (that means all the strings that already exist in the application), and an easy way to include newly added strings to the translations.

We need to organize a meeting where these questions will be addressed :

1. Scrutinize initial proposal #2647 
2. Decide on a standard format for errors, common between all the services
3. Decide on a tool/process (for example [gettext](https://en.wikipedia.org/wiki/Gettext)) to do the hardwork for us
4. How to handle missing required fields error message in django serializers
5. How to integrate that with what is already implemented in the front (i18next with a json dictionary) 
6. decide where and when translation should be performed (at first glance in the front)

**Comment by multun** [comment]
We discussed the matter with @flomonster @anisometropie @alexandredamiron @Math-R @eckter, and we came up with the following

## Error / warning format

This error format must be shared by all backend services.

```json
{
    "type": "invalid_detector",
    "message": "Invalid detector",
    "context": {
        "track_location": {"track": "toto", "offset": 42}
    }
}
```

## Handling operation failure / success

Sometimes, failure is not caused by a protocol error, but by the user request by itself.
The details of how failures are handled depend on the task at hand, so following this format is _not mandatory_.


### Example call failure

This is an example of how 

```json
{
    "status": "failure",
    "warnings": [],
    "error": {
        "type": "no_path_found",
        "message": "No path could be found",
        "context": {}
    }
}
```

### Example call success

```json
{
    "status": "success",
    "result": {}
}
```

## Error discovery

For each backend service, add a command which enumerates possible error types:

```json
[
    {
        "invalid_detector": {
            "message": "Invalid detector",
            "mandatory_context": ["track_location"],
        }
    }
]
```

This list of error messages can used to ensure error messages are properly translated / handled by the front-end.

Actions items:
- [ ] update the website documentation
- [ ] create a CI job which scraps backend error messages and reports the status of front-end translations
- [ ] migrate existing backend error messages
