### ISSUE TITLE
Dichotomy debugging

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#276]
We noticed that sometimes the dichotomy does not converge because the link between speed setpoint and running time does not seem to be continuous : a small change in the speed setpoint can result in a large change in the running time, and then the algorithm tries to converge towards a target time that can never be found.

We need to try to recreate a case where the dichotomy procces does not converge, and investigate the cause of the problem.

**Comment by axrolld** [comment]
We noticed that sometimes the dichotomy does not converge because the link between speed setpoint and running time does not seem to be continuous : a small change in the speed setpoint can result in a large change in the running time, and then the algorithm tries to converge towards a target time that can never be found.

We need to try to recreate a case where the dichotomy procces does not converge, and investigate the cause of the problem.
