### ISSUE TITLE
Pan/Zoom is not consistent for DataVizs (GET/GEV)

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#2774]
### Description and goal

Zoom works on ctrl-wheel, while pan works only with shift-mousdown

reason: on mac, ctrl-click trigger browser contextuel menu (+ prevent provide and behavior is not correctly disable on button release)

### Acceptance criteria

It is not convenient. Let's work with shift only

**Comment by nicolaswurtz** [comment]
I don't agree ! CTRL+Zoom is a common shortcut on whole operating systems, except MacOSX because... think different.

Here's my two cents, **we keep actual behaviour**:
- drag to move train on GET
- CTRL + drag to move chart (all charts)
- CTRL + mousewheel to zoom (all charts)
- CTRL + SHIFT + mousewheel to zoom horizontally (all charts)

For MacOSX, we should add a test to detect the OS and adapt shortcut. I'm not very familiar with MacOSX common shortcuts, but I think that Cmd is used in place of CTRL for the same shortcuts ? To be defined.

If test for OS is too heavy to be done inside a page, we could do it once for all in the head of the app and adapt shortcuts globally.

**Comment by axrolld** [comment]
Is there an agreement on @nicolaswurtz 's comment here ? Can we assign this issue to somebody or does it need more discussion ?

**Comment by clarani** [comment]
Will be fixed with the GET refacto
