### ISSUE TITLE
map: full screen button does not enlarge the map

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#3245]
### What happened?

Hitting the "fullscreen" button in the map in a scenario just folds down the top title bar instead of enlarging the map

https://user-images.githubusercontent.com/115472753/220137174-ceb6f145-6917-4264-be5b-d1bcd691749b.mp4

### What did you expect to happen?

The map should be enlarged or the button removed

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scenario
2. Scroll down to the map
3. Click on the fullscreen button

### What operating system, browser and environment are you using?

- **Browser**: Firefox v102.7
- **OS**: Windows 10
- **Env**: Dev

### OSRD version

1232050d

**Comment by bloussou** [comment]
It is even worse since if you have clicked on full screen and navigate back then you won't have the title bar in other part of the app:
[Screencast from 24-02-2023 17:41:26.webm](https://user-images.githubusercontent.com/32448554/221236540-ee7ee425-014d-494c-92e1-6801db998609.webm)
I'm bumping the severity since I though part of the app has crashed because I didn't found how to put back the title bar...

**Comment by nicolaswurtz** [comment]
It's a very old feature, that hasn't been used or tested since a very long time.
My two cents is that we should completely remove this feature — it could be part of my work along PI5, it's very linked.
