### ISSUE TITLE
front: hovering the graph crashes app

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#3250]
### What happened?

When hovering the pointer over the graph, it (seemingly) randomly crashes : 
https://user-images.githubusercontent.com/115472753/220143193-111dcc4b-c8ff-429a-95e8-9a6253ceba78.mp4

### What did you expect to happen?

The app should not crash

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scenario page
2. add a train
3. Hover the mouse over the GET

### What operating system, browser and environment are you using?

- **Browser**: Firefox v102.7
- **OS**: Windows 10
- **Env**: Dev

### OSRD version

 1232050d

**Comment by eckter** [comment]
I changed the severity to critical, it makes it nearly impossible to add trains

**Comment by Tguisnet** [comment]
This bug is very annoynig, if you try to go on my project (tibo loves tiger), then on my study : "new line for tigers", then on my scenario : "test of my new infra !"; I get a whitepage every time I hover the graphs !
![image](https://user-images.githubusercontent.com/27173221/220917525-2dab4771-a794-49f4-a715-f4eb27180ee4.png)

**Comment by celine-sncf** [comment]
Can't reproduce today

**Comment by Tguisnet** [comment]
Can't reproduce too

**Comment by celine-sncf** [comment]
Reproduced on my scenario : miaou/mew mew/hss
