### ISSUE TITLE
Editor : wrong cursor when placing an object

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#3393]
### What happened?

When we try to create an object, the cursor to move on the map is displayed, not the cursor to select/create an object.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/27173221/223023010-7eef20b6-8cb7-467d-8604-935f083b2da8.png)

### What did you expect to happen?

We should have an appropriate cursor when we try to create an object

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the editor
2. try to create a point object

### What operating system, browser and environment are you using?

- **Browser**: Chrome v110
- **OS**: Windows 10
- **Env**: Dgex dev

### OSRD version (top right corner `Account` button > `Informations`)

7bf8785

**Comment by jacomyal** [comment]
I used the `"move"` CSS cursor, since when you create a new point object, you are grabbing it by default, basically. The thing is on my Ubuntu Firefox, this cursor is displayed as a grabbing hand, while it should indeed be displayed as the cross you see ((at least according to [this](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor)).

@Tguisnet If I switch to the `"grabbing"` value (so you would see a grabbing hand as I do), would it be OK for you?

**Comment by SharglutDev** [comment]
Tested on chrome (nixos) and firefox (macOS) and the cursor is also the cross one. We need your reply @Tguisnet for the cursor you want.

**Comment by Tguisnet** [comment]
@jacomyal Yes, I think the grabbing hand is ok.
