### ISSUE TITLE
Front: unable to dismiss new dropdown component when clicking outside

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#3753]
### What happened?

If we click in the following area, the dropdown doesn't dismiss (I think detection is made on a layer not taking whole window)

![image](https://user-images.githubusercontent.com/6003856/228923215-f1feb0b4-7e7d-40c1-ac7d-6e0c41a4001d.png)

### What did you expect to happen?

Dropdown dismiss everytime we click outside, everywhere

### How can we reproduce it (as minimally and precisely as possible)?

Click in the red zone one the capture when navbar dropdown is opened

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

0123456

**Comment by sim51** [comment]
Issue appears only when the document doesn't take 100% of the screen.

@nicolaswurtz can I update this rule https://github.com/DGEXSolutions/osrd/blob/dev/front/src/styles/scss/_body.scss#L2 by `body { min-height: 100vh; }`  ?

I don't know why this rule has been written initially, that's why I'm asking the question.
