### ISSUE TITLE
Slight offset between train position and signals in GET

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#3822]
### What happened?

When zooming on the GET, it appears that there's sometimes a slight offset here, between the position of the head of the train and the signal changing color :
![image](https://user-images.githubusercontent.com/86296016/230104837-071bb8e5-adf9-4233-8e72-c4166d8cdd0d.png)
which can sometimes reach ~30s.

### What did you expect to happen?

The moment the signal changes color must match exactly the moment the head of the train enters the block section, or the moment the tail leaves it.

### How can we reproduce it (as minimally and precisely as possible)?

1. Display any train on a GET
2. Zoom quite a lot and check every signal transition, you should see some offsets between 0 and ~30s sometimes

### What operating system, browser and environment are you using?

Browser: Chrome Version 111.0.5563.147
OS: Windows 10 build 19045.2728
Env: Dev

### OSRD version (top right corner `Account` button > `Informations`)

6cf0ea12

**Comment by Khoyo** [comment]
I'll investigate it, but note that in real infrastructures this isn't the case. The signal only changes color when the train cross the detector, which is usually placed after the signal, not right under it.

Right now detectors are generated right under signals, so it shouldn't be the case. I'm guessing this is due to bad interpolation of the train posiition curve.

**Comment by axrolld** [comment]
Yes i'm also guessing this is due to the representation of the train position, but i have no proof.

Thanks for investigating this !

**Comment by celine-sncf** [comment]
@axrolld can you reproduce today ?

**Comment by Khoyo** [comment]
could not reproduce
