### ISSUE TITLE
longitudinal section get out of frame

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#4312]
### What happened?

![image](https://github.com/DGEXSolutions/osrd/assets/55697888/3895431a-8893-405a-8aba-db7204721d6f)

### What did you expect to happen?

The longitudinal section (red line) must stay in the frame 

### How can we reproduce it (as minimally and precisely as possible)?

Create a train and see the gradient, radius and longitudinal section frame

### What operating system, browser and environment are you using?

- **Browser**: Firefox v113
- **OS**: Ventura
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

Editoast 	 e5481800 Core 	 e5481800 API 	 e5481800 Front 	 e5481800

**Comment by axrolld** [comment]
May I suggest a fix for this bug, that would result in an enhancement of this graph until we start using the new component : 

There a 3 data represented on this graph, each one with its own unit : 
- slopes (m/km)
- curvatures (m, i guess ?) -> The unit isn't clear cause only the slopes unit is displayed
- relative altitude difference (m) -> Same, the unit isn't visible)

In order to fix the scale problem and start fixing the invisible units problem i suggest first creating a second axis to the right of the graph, with the relative altitude difference in meters. This would not fix the curvatures but that could be another issue.

This suggestion would result in the following acceptance criterias : 
- [ ] A second axis has been created to the right of the graph, with unit in meters
- [ ] The relative altitude curve and its relative axis (the one to the right) are auto-scaled so that the curve fits entirely

**Comment by SharglutDev** [comment]
@axrolld Should we scale to the right the positive numbers so they can be aligned with the negative numbers ?

![Capture d’écran 2023-12-07 à 14 36 11](https://github.com/osrd-project/osrd/assets/113104137/007cf269-e8b5-4bb1-a3ab-185ed735545f)

**Comment by axrolld** [comment]
I think that would make sense yes

**Comment by axrolld** [comment]
Removed the `good first issue` label because this was no piece of cake !

**Comment by axrolld** [comment]
Tried it on `dev`, it works well on the first train of the list


![Image](https://github.com/osrd-project/osrd/assets/86296016/b7cb41ea-6206-4ee2-a28f-a9811f693fad)


But not on other trains that don't have the same path :


![Image](https://github.com/osrd-project/osrd/assets/86296016/3af95ee7-18a0-4815-ace7-d62e11c93737)

**Comment by axrolld** [comment]
Also, tiny detail but the unit `m` should be rotated by 90° to match the m/km/h display :


![Image](https://github.com/osrd-project/osrd/assets/86296016/5b28b328-55f1-49f0-b70c-4550c86cb5c2)

**Comment by clarani** [comment]
Not relevant anymore, opened a new issue #8095
