### ISSUE TITLE
Use SNCF Opendata data to complete OSM fr

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#4803]
https://github.com/orgs/osrd-project/projects/12/views/7?pane=issue&itemId=31750821

**Comment by Tristramg** [comment]
The task is a bit tricky

The geolocation of the sncf opendata isn’t precise enough to be confident. They are defined as km along a track. Because of track changes (constructions, new layout…) those km should be considered like a postal address and can’t be used confidently to compute the position.
Access to the railway are also difficult so it won’t be possible to check on the field.

We could maybe do a specific interface with aerial images in order to place precisely missing data if there is no ambiguity, but this would require about 100 000 placement by hand.
