### ISSUE TITLE
Wrong GET projection

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#4920]
### What happened?

The projections seem broken since sometimes it's possible to see both trains even if they're not on the same track.

Here is an example of a small infra.
![image](https://github.com/osrd-project/osrd/assets/15349030/f0c23a76-94f9-4f93-90ca-c1050fccd1d6)

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario
2. Create a train `A` on a main track
3. Create a second train `B` taking a detour

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local & dev

### OSRD version (top right corner `Account` button > `Informations`)

1e94853a31ec9e9ed87f7534f1ea27018c4d511e

**Comment by younesschrifi** [comment]
Can't reproduce the bug. 
I added 2 trains with the same departure and arrival points, except that one of these 2 trains took a diversion. Everything works fine. When the trains are not in the same track we can see that one of the two trains has an empty space (because the path of the other train is chosen as the reference)

![Image](https://github.com/osrd-project/osrd/assets/75369238/addfbe9e-109e-440a-9d49-cb0fbd74bbe6)
