### ISSUE TITLE
Fail to create a train with an electrical rolling stock created from scratch

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5315]
Step to reproduce:
1. Create a new viable electrical rollingstock from scratch
2. Save it
3. Check if you can create a train with this rolling stock, pathfinding should fail with `assertion failed`

version: `e32e129131ada79b92704fc7ca6bf137888e8489`

**Comment by Castavo** [comment]
I don't know if this error happens for thermal only rolling stocks, but for electric rolling stocks, it is due to the fact that the fields `electrical_power_startup_time` and `raise_pantograph_time` are set to null indiscriminately in new rolling stocks in the RS editor.

I believe they should be editable or at least set to 0 when the train is electric

**Comment by bloussou** [comment]
Still broken

**Comment by axrolld** [comment]
@anisometropie are you ont it ?

**Comment by flomonster** [comment]
## How to fix

We discussed a number of things that could be done to correct this bug. The chosen solution is as follows:

- The frontend should set `electrical_power_startup_time` to `5.0` and `raise_pantograph_time` to `15.0` when the RS is electrical
- Editoast should adapt its deserialization validating that these a value are provided when the train is electrical.

**Comment by bloussou** [comment]
@anisometropie @clarani any update on this ?

**Comment by axrolld** [comment]
A PR from @anisometropie should arrive soon
