### ISSUE TITLE
Speed limits data is missing

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#547]
TLDR: We need to fix the import script to have all data about speed limits.

**Comment by flomonster** [comment]
Can you specify if the speed limit is present but not respected by the train or if there is no speed limit?

- If the train does not respect the speed limit can you provide information on the path to reproduce the bug.
- Otherwise, if there is missing data then it may be an error in the process that imports the data.

**Comment by nicolaswurtz** [comment]
There is no line speed limit on any path, data seems to be missing anywhere (with some exceptions).

When testing on line with speedlimit shown in map, speedlimit is respected.

This is the map with speedlimits :
![image](https://user-images.githubusercontent.com/6003856/152997248-c932c2bd-0d93-42ea-9cb2-39ef38543ddd.png)

**Comment by flomonster** [comment]
a fix in the infrastructure import allows to get this coverage:

![2022-04-19-173844_1009x873_scrot](https://user-images.githubusercontent.com/15349030/164054113-9084b85a-7247-4a54-9147-5ed166b96b2c.png)

(Red means no speed limits)
