### ISSUE TITLE
Add a standardized error system through the api

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#557]
Any assert or exception result in a 500 despite many being caused by invalid user inputs. We need to find a way to filter those

**Comment by flomonster** [comment]
# What are the requirements of our error system?

This article (https://nordicapis.com/best-practices-api-error-handling/ ) gives some guidelines and examples used in the industry.
Here is a summary of best practices:

- Have a human readable message
- Have a documented error code (used by the machine to handle the error). 
- Explain not only what the error is, but provide information on how to fix it.

# Proposition

Here is a proposition of error inspired by the facebook api.

### Request
`POST` : `http://gateway.dev.dgexsol.fr/osrd/train_schedule/standalone_simulation/`

### Response

`400 Bad Request`

```json
{
  "error": {
    "type": "MarecoDidNotConverge",
    "code": 4242,
    "message": "An allowance could not be applied because the mareco algorithm did not converge. To fix this reduce the value of the allowance.",
    "help_url": "https://osrd.fr/doc/../errors/4242/"
    "allowance_index": 1
  }
}
```

# Implementation

```java
public abstract class OSRDError extends RuntimeException {
    public final int code;
    public final String message;


    protected OSRDError(int code, String message) {
        this.code = code;
        this.message = message;
    }

    public static final JsonAdapter<OSRDError> adapter = new Moshi.Builder()
            .add(PolymorphicJsonAdapterFactory.of(OSRDError.class, "type")
                .withSubtype(MarecoDidNotConverge.class, "MarecoDidNotConverged")
            )
            .build()
            .adapter(OSRDError.class);
}
```

```java
public class MarecoDidNotConverge extends OSRDError {
    @Json(name = "allowance_index")
    public final int allowanceIndex;

    public MarecoDidNotConverge(String message, int allowanceIndex) {
        super(4242, message);
        this.allowanceIndex = allowanceIndex;
    }
}
```

**Comment by axrolld** [comment]
That looks great ! It will definitely make debugging way easier that way, especially for people that are not super familiar with the project !

**Comment by loic-hamelin** [comment]
Awesome :)

**Comment by multun** [comment]
I'm a little big worried about the integer error codes. I'd rather use strings so we can try our best to avoid collisions. looks great otherwise

**Comment by flomonster** [comment]
@multun It looks standard to use both a numeric error code and a string. However you are right, the proposed implementation does not ensure the unicity of the code. I don't see an easy way to fix that unless using metaprog.

**Comment by multun** [comment]
@flomonster IMO the error code just needs to be unique, and it is easier to ensure no clashes occur with strings. In order to avoid exceedingly frequent clashes, people do not allocate numeric error codes sequentially. Instead, they define per-module prefixes (like 2XX for HTTP, or [this stuff in iPXE](https://github.com/ipxe/ipxe/blob/master/src/include/ipxe/errfile.h)). iPXE and HTTP both do this to save bandwith / memory (iPXE has some more reasons which are related to C). I don't think it applies to us. All of the occurrences of numeric error codes I've come across have a centralized registry for error codes or error code prefixes.

This is a pain:
 - You need to have a way to ensure your error codes don't clash, which isn't easy to do in java, as classes are lazily loaded
 - You've got to statically allocate integer error codes, otherwise error codes aren't stable, and thus pointless
 - That means we can't even both load plugins and be kind of confident there are no clashes

Using string error codes makes it much easier to have hierarchical and hopefully conflict free identifiers, like so: `osrd:mareco:convergence` (or just `mareco:convergence`)
