### ISSUE TITLE
front : editor : track editor : impossible to move a point at the end of the track

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#5659]
### What happened?

When you try to move a point at the end of a track section, you can not save

![Image](https://github.com/osrd-project/osrd/assets/55697979/378cb82f-998d-493b-b283-31177b420881)

### What did you expect to happen?

you can push the button to save and a message should say that the modifications are saved 

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to "selection" tool and select a track
2. Click on the button to edit it 
3. Move a point at the end of the track to extend the track
4. Push the button to save 

### What operating system, browser and environment are you using?

- **Browser**: Chrome 
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

7f3a1138

**Comment by sim51** [comment]
## Scenarii

* moving the last node of a tracksection works 
* moving a point in the middle of tracksection fails with the error 

JSON Patch sent : 
```
[
	{
		"obj_id": "686dd45e-6667-11e3-81ff-01f464e0362d",
		"obj_type": "TrackSection",
		"operation_type": "UPDATE",
		"railjson_patch": [
			{
				"op": "replace",
				"path": "/sch/coordinates/2/1",
				"value": 44.87670028576295
			},
			{
				"op": "replace",
				"path": "/sch/coordinates/2/0",
				"value": 1.2226903438568115
			},
			{
				"op": "replace",
				"path": "/loading_gauge_limits/3/end",
				"value": 264.12150982380194
			},
			{
				"op": "replace",
				"path": "/loading_gauge_limits/3/begin",
				"value": 90.12150982380197
			},
			{
				"op": "replace",
				"path": "/loading_gauge_limits/2/end",
				"value": 264.12150982380194
			},
			{
				"op": "replace",
				"path": "/loading_gauge_limits/2/begin",
				"value": 90.12150982380197
			},
			{
				"op": "replace",
				"path": "/loading_gauge_limits/1/end",
				"value": 264.12150982380194
			},
			{
				"op": "replace",
				"path": "/loading_gauge_limits/1/begin",
				"value": 90.12150982380197
			},
			{
				"op": "replace",
				"path": "/loading_gauge_limits/0/end",
				"value": 264.12150982380194
			},
			{
				"op": "replace",
				"path": "/length",
				"value": 267
			},
			{
				"op": "replace",
				"path": "/geo/coordinates/2/1",
				"value": 44.87670028576295
			},
			{
				"op": "replace",
				"path": "/geo/coordinates/2/0",
				"value": 1.2226903438568115
			}
		]
	}
]
```

API response: `{"status":400,"type":"editoast:operation:InvalidPatch","context":{},"message":"A Json Patch error occurred: 'Operation '/0' failed at path '/sch/coordinates/2/1': path is invalid'"}`

* moving the start point of tracksection has the same effect than moving a point in the middle.

## Root cause analysis

In the frontend, when we update an object, we compare the original and the newly object so we can produce a JSON patch. 

In fact on the original one, we override the schematic data with the geo one. We thought that geo & sch were sync for now, but it's not the case. 

Example :  if we have an empty schematic in the original, with our code, we supposed that it was equal to the geo, and so the produced JSON patch is not valid against the original data : we do some `replace` operation instead of `add` operations in this case. Doing a replace on a data that doesn't exist produce an invalid path exception.
