### ISSUE TITLE
Front: Editor: Strange behaviour for the range editor.

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#5708]
### What happened?

When we try to edit a range (for example, curves in a tracksection), the requests from the range editor to the backend are strange.
If we try to replace a value, **with multiple ranges** : 
- some fields that are not concerned are replaced;
- the field we want to replace is add

example shown below -> trying to replace the value of range 5000-10000 by 3
![image](https://github.com/osrd-project/osrd/assets/27173221/f1cf7d2a-563d-494e-bdf8-7063b20418ec)

what's more, when we try to merge 2 range together, some "ghost" ranges are deleted (ghost means not visible for the user)
(this deletion could be related to the previous strange add)
and sometimes, nothing is deleted or changed during a merge

example shown below -> 2 ranges, but remove of one range during merge
![image](https://github.com/osrd-project/osrd/assets/27173221/e5295632-5e96-4180-95cd-3810e1c5d009)
![image](https://github.com/osrd-project/osrd/assets/27173221/9baa360c-cceb-4727-b950-91c0656d21b8)

example shown below -> merge of 2 ranges but there is just a replace
![image](https://github.com/osrd-project/osrd/assets/27173221/aa7d7cf5-70fc-4e30-9b24-ac314ed0575f)

Last problem : sometimes (it's difficult to reproduce it), the patch in the request is empty when we try to edit a range.
The front show modifications, but the back is not up to date, so nothing happened when we refresh the page.

example shown below -> try to merge ranges, but the patch is empty.
![image](https://github.com/osrd-project/osrd/assets/27173221/d9a488a5-a440-4e6d-95a7-f3a1b703f729)

### What did you expect to happen?

Normal requests, and normal behviour when editing a range

### How can we reproduce it (as minimally and precisely as possible)?

(already explained in the description)

### What operating system, browser and environment are you using?

- **Browser**: Firefox v119
- **OS**: Windows 10
- **Env**: Dgex Dev

### OSRD version (top right corner `Account` button > `Informations`)

c71bf379

**Comment by sim51** [comment]
This is my understanding of the linear metadata feature (for curves, slopes, ...) on track sections : 

* A track section must be fully covered by a linear metadata. We normally should not have gaps.
* Gaia has some gaps in its data, and also has some invalid data (data overlaps, out of range, ...)
* On a track section imported from Gaia, a user should be able to modify some attributes and save them, even if linear metadata  are not valid (and if they have not been modified)

In the code, we have a function that do some fixes on the data, so we are able to use and display them.  I think that's why you have some json path that you find strange. 

BUT, I have reproduced the issue on merging two segment in one, once ... I don't know how to replicate the issue. I need to find a reproducible scenario

**EDIT:**

Try to find the scenario, and I think it's this one : 
- split the track section in two segments. Make the left one with a value of `0`, and the other one with a value of `10` for example. 
- save the track section
- select the right segment
- click on `merge in left`
- save
- click on the select tool
- (re)-select the track section and edit it 

You should still see two segment and not one
