### ISSUE TITLE
Editor : button to create LPV is not activated

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#5842]
### What happened?

There is a button to indicate that the new speed section is a LPV but this is not activated till you save the new speed section value.

![Image](https://github.com/osrd-project/osrd/assets/55697979/0d89635e-142c-4233-b7aa-5790d73ea0c0)

### What did you expect to happen?

Two possibilities : 1. the button will appear when the value is saved, 2. the button is activated from the begin

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the editor
2. Select the speed section edition tool
3. Insert a speed value and try to tick the LPV case

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

11bf1b7

**Comment by sim51** [comment]
@bgiuliana  I will say it's not a bug it's a feature :)

When you click on this checkbox when there is no selected track ranges, it does nothing (because we lack some data to enable the PSL).

Code is here : https://github.com/osrd-project/osrd/blob/dev/front/src/applications/editor/tools/rangeEdition/components.tsx#L317-L341

SO what I purpose is to disable or hide this checkbox when no track range is selected.
