### ISSUE TITLE
Per-object urls in the infrastructure editor

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#5956]
### Who would benefit from this feature?

Everyone

### What is this feature about?

- adding object specific urls in the editor
  - For example "editor/{infra_id}/{object_type}/{object_id}

### Why is this feature valuable?

This feature matters because it:
- enables having a history of objects modified in the navigator, and would make navigation easier
- enables sharing objects data / position more easily

**Comment by SharglutDev** [comment]
### AC 
- [ ] a `editor/{infra_id}/{object_type}/{object_id}` url model should select the concerned object and focus on it
- [ ] if one the params is incorrect, it should redirect to a 404 page
- [ ] the 404 page should either propose to go back to the previous page or go back to the editor home page
- [ ] selecting an single object on the editor map should redirect the url with the above url model

**Comment by clarani** [comment]
### AC changed
- [ ] when selecting an object or many objects, the url gets updated with the objType and its id (ex: `http://localhost:4000/editor/1?selection=objType%id`)
We use search params because we usually change the complete route when we change page (but its not the case here)
- [ ] if we share an url containing selection of objects, these get selected
- [ ] if the url is invalid, display error message to the user and redirect to the editor home page
- [ ] if the selection is too long (more than 100 objects), the url shouldn't be updated to prevent any browser error
- [ ] when switching tool, the url should be cleaned if there was a selection
- [ ] when creating a new object, the url should be updated with this new object infos
- [ ] after creating an object or if we are editing one, pressing the "create new object" should clean the url

### Some questions
- when we select an object and click on a button to create a new obj (for instance, select a trackSection and click on the button to edit a signal), the object is still selected in the url but it does not make sense ✅ 
- when we create a new object, the url should be updated so we can share it and see its id ✅
