### ISSUE TITLE
Delete an infra is too long

### ISSUE THREAD

**Issue by younesschrifi** [OpenRailAssociation/osrd#6064]
### What happened?

Deleting an infra is too long (25 min for infra France) 

### What did you expect to happen?

Deleting an infra should be faster

### How can we reproduce it (as minimally and precisely as possible)?

Try to delete an infra

### What operating system, browser and environment are you using?

- **Browser**: Chrome v109
- **OS**: MacOS M1
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

0adc3bc

**Comment by flomonster** [comment]
## How to fix (CR @leovalais @younesschrifi @flomonster)

- Remove psql triggers
- Stop creating triggers from the search migration generator
- Add new generated data (one for each search table)
- Move the SQL query that generates all rows for a given infra to the generated_data interface.
  - We might need to use (obj_id, obj_type instead of primary key)
- Adapt the SQL query for update (only update required rows)

This should fix this bug too: https://github.com/osrd-project/osrd/issues/3888

**Comment by bgiuliana** [comment]
in addition, when we have deleted the infra is still in the list
