### ISSUE TITLE
Moving a train on GET shouldn't refresh all simulation

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#6095]
# Description

When moving a train on GET, all simultation results is refreshed.
For 55 trains (60min, 12 stops) the endpoints respond in: 
- patch < 1s
- conflict < 1s
- train_schedule_results > 16s
- whole page draw ~1s

Front shouldn't request refresh of all simulation, neither the back side nor the front side.

Several way could be chosen:
- only refresh the updated train (documentation with RTK: https://redux-toolkit.js.org/rtk-query/usage/automated-refetching#advanced-invalidation-with-abstract-tag-ids)
- only patch on backend and change time values on frontend

**Comment by axrolld** [comment]
> Several way could be chosen:
> 
> only refresh the updated train
> only patch on backend and change time values on frontend

Has something been decided between those two options yet ?

**Comment by SharglutDev** [comment]
We will be going with the first option

**Comment by SharglutDev** [comment]
After some testing, the idea for the first option can't be implemented, this rtk query feature doesn't fit our needs because of the way the app is builded and especially the `getTrainScheduleResults` endpoint.

So after some discussions, it has been decided to change this endpoint to fit our needs. We need to be able to decide which train(s) we want to (re)fetch when entering a scenario or adding/updating/deleting a train and not call the whole results each time.

### Technical AC
**Back**
- [ ] getTrainScheduleResults should now require an array of train ids (the trains we want to fetch) instead of timetable id
- [ ] throw an error if the train id is from a different timetable

**Front**
- [ ] getSimulationResults() should now require an array of train ids (the trains we want to fetch) instead of timetable id
- [ ] a [trainResultsToFetch, setTrainResultsToFetch] state (array of train ids) should be created in Scenario.tsx
- [ ] StdcmRequestModal should provide the timetable train ids to the new endpoint
- [ ] adding a train (SubmitConfAddTrainSchedules.tsx) should setTrainResultsToFetch with the new train ids
- [ ] duplicating a train (TimetableTrainCard.tsx) should setTrainResultsToFetch with the new train id
- [ ] updating a train (SubmitConfUpdateTrainSchedules.tsx) should setTrainResultsToFetch with the new train id
- [ ] deleting a single train (TimetableTrainCard.tsx) should not call the endpoint but rather update the simulation with the new list of remaining trains
- [ ] deleting many trains (Timetable.tsx) should not call the endpoint but rather update the simulation with the new list of remaining trains
- [ ] updating the projection (TimetableTrainCard.tsx) should setTrainResultsToFetch with all train ids
- [ ] deleting the projected train, when there isn't anymore train with the same path, should setTrainResultsToFetch with the train getting the projection
