### ISSUE TITLE
Save with 'enter' button doesn't take the last modified value in the form

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#6503]
### What happened?

We could save a form with the 'enter' button.
However, if we modify a form, the last value which is modified is not sent in the payload.
We have to use one more time the 'enter' button
(first input save the value for the form, second input save the value in the db with the payload)

### What did you expect to happen?

If we use the 'enter' button, it should save directly the new values the first time we press the keyboard.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the editor
2. try to modify a form of an object
3. save with the 'enter' button

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: All

### OSRD version (top right corner `Account` button > `Informations`)

ef4a364

**Comment by sim51** [comment]
@Tguisnet I can't reproduce this issue 

What I did is : 

- go to the editor
- display switches
- select a switch
- edit it
- click on the label input field
- change its value
- press tab
- change the value of "group change delay"
- press enter

I checked that the generated JSON patch  is good as well as the return of the api, and it's OK

I don't know if the issue is already solve or if I do something wrong in my scenario

**Comment by Tguisnet** [comment]
@sim51 I can't reproduce it for now, it seems to me this was probably fix
