### ISSUE TITLE
front: irrelevant infra retrieval error popup when empty database

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#6541]
### What happened?

When you open reference map with no infra in database, an error popup fires and says: "Unable to retrieve infra".
This is normal: there's no infra at all!

### What did you expect to happen?

This is not an error, there should be no error messages.

### How can we reproduce it (as minimally and precisely as possible)?

1. use OSRD without any data
2. go to reference map
3. see the popup
4. be completely stunned

### What operating system, browser and environment are you using?

- **Browser**: Firefox v123.0b3
- **OS**: Archlinux latest
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

e220992

**Comment by axrolld** [comment]
@Caracol3 will take this in charge after his current task.

**Comment by sim51** [comment]
Carto module takes the infra we've got in the store. 

If there is none, we don't have the toast message, but we do some calls to editoast with `infra=undefined` which leads to some 404 in the network panel (we should solve that).

We have the error when we open the infra module selector modal. due to this code : 
https://github.com/OpenRailAssociation/osrd/blob/dev/front/src/modules/infra/components/InfraSelector/InfraSelector.tsx#L18-L38

IMHO, this code is not needed, it's not the role of this component to check that the current infraID can be loaded, but just to allow the user to select a new infra.
