### ISSUE TITLE
`The requested train stopped before reaching its destination (not enough traction)` on a Paris - Grenoble train

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#6816]
### What happened?

# Inputs

## Rolling stock
2TGVDUPL

## Route
`PLY SXA GE` with a 120s stop in `SXA`

![image](https://github.com/osrd-project/osrd/assets/86296016/d97d485a-3d19-4307-86d6-c6c6e3295039)

> [!NOTE]
> Don't mind the Pompadour-Maison-Alfort, it's another bug

## Margins
4.5mn/100km, then 5%, then 4.5mn/100km again. Values of transitions on screenshot:
![image](https://github.com/osrd-project/osrd/assets/86296016/9b57b455-a2a3-47e4-89b0-b2fd6fa3c266)

## Simulation parameters
![image](https://github.com/osrd-project/osrd/assets/86296016/13df99d9-1a92-4a1d-93a1-3cd0f5e9a557)

# Output
`The requested train stopped before reaching its destination (not enough traction)`

![image](https://github.com/osrd-project/osrd/assets/86296016/f60ec27f-97a0-4e4a-9690-83f262f90068)

### What did you expect to happen?

I'm expecting the train to work.

### How can we reproduce it (as minimally and precisely as possible)?

1. Reproduce the steps above.

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: staging internal

### OSRD version (top right corner `Account` button > `Informations`)

1f27b88

**Comment by bougue-pe** [comment]
To sum up: ✔️  my guess is that it's been **fixed** (unreleased) since `v0.2.12` in #7529 by @eckter.
OK on `dev` branch from 2024/06/27, and KO on `v0.2.12` (with a little different message than the 3-months old issue).

----

On TSv1 (Not easily doable on TSv2 it seems, but probably the same status):

✔️ Not reproducible on dev.dgexsol, infra France (operational study) 435263b
Only difference is this warning ![image](https://github.com/OpenRailAssociation/osrd/assets/150040524/46623967-5142-4309-8012-2e883340c84c)
See https://osrd.dev.dgexsol.fr/operational-studies/projects/37/studies/89/scenarios/214
(distance changed a tiny bit, ~20m removed (553743m)

✔️ Same goes for staging.dgexsol, same version (https://osrd.staging.dgexsol.fr/operational-studies/projects/35/studies/33/scenarios/63)

✔️ Same goes for dev-osrd.reseau, same version (https://dev-osrd.reseau.sncf.fr/operational-studies/projects/4/studies/5/scenarios/16)

❓ rec-osrd.reseau is down for core (and no infra selectable), same version.

❌ "Reproduced" (not exactly the same message) on int-osrd.reseau `v0.2.12` 21906b8 (https://int-osrd.reseau.sncf.fr/operational-studies/projects/12/studies/21/scenarios/58)
The error I get there is `Assert error at CoastingGenerator.java:71: {{assert_message}}`
