### ISSUE TITLE
Number of trains in scenario / scenario in study / studies in project requires refresh to be updated

### ISSUE THREAD

**Issue by maelysLeratRosso** [OpenRailAssociation/osrd#7181]
### What happened?

I have a project with one study : 

![image](https://github.com/OpenRailAssociation/osrd/assets/156183612/e94690fa-997f-4318-9de5-5f395ca6d2c4)

I create a second study in this project, and go back to the project page : the number of studies is still 1 (instead of 2)

![image](https://github.com/OpenRailAssociation/osrd/assets/156183612/e6906851-942e-46ec-8527-68f56df0f1a0)

If I refresh this page, the number becomes 2 (correct):

![image](https://github.com/OpenRailAssociation/osrd/assets/156183612/403bc3a8-6470-463e-8079-57aa80e82919)

The problem is the same with : 
- number on scenario in study
- number of trains in scenario

### What did you expect to happen?

I expect the number of studies to be the new number without refreshing the page

### How can we reproduce it (as minimally and precisely as possible)?

Follow the steps in the description

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: String internal

### OSRD version (top right corner `Account` button > `Informations`)

dev a42cad3

**Comment by emersion** [comment]
Hmm. A way to fix could be to invalidate studies/projects from the cache when creating a scenario:

```patch
diff --git a/front/src/common/api/osrdEditoastApi.ts b/front/src/common/api/osrdEditoastApi.ts
index 922e04b9f483..c8d15479158f 100644
--- a/front/src/common/api/osrdEditoastApi.ts
+++ b/front/src/common/api/osrdEditoastApi.ts
@@ -840,7 +840,7 @@ const injectedRtkApi = api
           method: 'PATCH',
           body: queryArg.scenarioPatchFormV2,
         }),
-        invalidatesTags: ['scenariosv2'],
+        invalidatesTags: ['scenariosv2', 'studies', 'projects'],
       }),
       getV2Timetable: build.query<GetV2TimetableApiResponse, GetV2TimetableApiArg>({
         query: (queryArg) => ({
```

I don't think manually mutating the count in the cache is a great solution, because this also applies to other fields (e.g. updated_at), and we'd need to do this correctly in numerous places in the same way that the server does.

At a minimum, this patch would need to get replicated to other similar requests as well. This could also be more granular and only invalidate the single study/project/scenario with the specific ID we're editing. That probably won't help too much with the HTTP request count though.

However, it would be better to instead update our cache with the response from the server. The response contains the updated study/project/scenario so we could just use that instead of invalidating.

**Comment by emersion** [comment]
Ah, snap, that file is actually generated code. So we'd need to apply these changes via `api.enhanceEndpoints()` on top of the generated stuff.
