### ISSUE TITLE
Weird pathfinding failure

### ISSUE THREAD

**Issue by maelysLeratRosso** [OpenRailAssociation/osrd#7367]
### What happened?

I tried to create a train (bimode) in this zone : https://rec-osrd.reseau.sncf.fr/map/43.5095/5.1663/18.9188/0/0 on France infrastructure, with the following coordinates for the steps (on the right-side track): 
- departure : [5.166198139826849, 43.50955610935122]
- arrival : [5.166478327087751, 43.50936901134764]
![image](https://github.com/OpenRailAssociation/osrd/assets/156183612/282e4428-165e-4efe-8684-62d06c81585a)

and the pathfinding failed, with no obvious explanation

### What did you expect to happen?

I expected the pathfinding to succeed

### How can we reproduce it (as minimally and precisely as possible)?

Follow the steps above

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: Staging internal

### OSRD version (top right corner `Account` button > `Informations`)

949d616

**Comment by Castavo** [comment]
I managed to replicate the problem, I also saw that by offsetting the end of the PF, it works:

![Image](https://github.com/OpenRailAssociation/osrd/assets/47494402/9641d2af-05f5-4785-9263-d5b74a3b38fd)

It's probably linked to a data error, and to the itinerary generation specifically (which maybe goes wrong because of the signals)


![Image](https://github.com/OpenRailAssociation/osrd/assets/47494402/4438d6c6-004d-40eb-a84c-1fc4589922a7)

The fact that there are two CARRE facing each other on this track (the lower one) seems shady to me.

**Comment by maelysLeratRosso** [comment]
cannot reproduce
