### ISSUE TITLE
front: TSv2: odd behavior of the checkbox of reception on closed signal

### ISSUE THREAD

**Issue by younesschrifi** [OpenRailAssociation/osrd#7586]
### What happened?

Sometimes, when we click on the checkbox, it doesn't work. 

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario
2. Go to "horaires et marges"
3. click on the checkbox of "reception sur signal fermé"
4. See the odd behavior

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: Windows
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

625d185

**Comment by SharglutDev** [comment]
It usually happens when trying to check a operational point close to the origin because sometimes the operation points returned by the path properties endpoint contains several elements at position 0. However we should not be able to set a constraint on the origin.

To solve this, we should remove all operational points at position 0 that are not the origin selected by the user.

**Comment by SharglutDev** [comment]
More to modify/clarify on the times and stops table : 
- The origin should always be the first operational point in the table (even if there is multiple ops with position 0)
- For the origin, all fields are updatable, except the arrival_time that should match the departure_time of the train but we still need to send a null arrival to the back
- For the destination, the "reception on closed signal" field should not be disabled for obvious reason as well as the stopFor
- Origin and destination rows should not have the "remove via" button (red cross icon) at the end of the row
