### ISSUE TITLE
simlation stops input table: emptying a cell makes an  invalid row

### ISSUE THREAD

**Issue by anisometropie** [OpenRailAssociation/osrd#8123]
### What happened?

Removing the last editable value in a row doesn’t delete the row from the path steps. the row remains grayed, and is only really removed when we press the red X on the right.

The value of the cell is `null` instead of `undefined` and it’s enough to make the row considered not deleted.

https://github.com/user-attachments/assets/204a8792-5743-462e-9a61-a8a2db1aacc0

### What did you expect to happen?

if all the cells become empty, the row should be deleted.

### How can we reproduce it (as minimally and precisely as possible)?

cf video

### On which environments the bug occurs?

Local

### OSRD version (top right corner `Account` button > `Informations`)

580140d68159ed3b858569e5278dc5022d0ec53a

**Comment by anisometropie** [comment]
This seems to work as intended, can you confirm @clarani @SharglutDev

**Comment by SharglutDev** [comment]
> This seems to work as intended, can you confirm @clarani @SharglutDev

Yep for me with the current use of the input table, it shouldn't be removed from pathSteps because if it's an op added by map click and we remove it, it might affect the pathfinding.

I don't know where but I think an issue has been created to change the behavior and to make a distinction between an step required for the path and others that can get constraints.

So I think we can close this issue for now. (@axrolld is that ok for you ?)

**Comment by axrolld** [comment]
Yep it's [this one](https://github.com/osrd-project/osrd-confidential/issues/574), but we agreed that the overall behavior was very unclear but even this ticket got closed. The entire subject needs deeper refinement.
