### ISSUE TITLE
Missing path item on map for invalid train schedule

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#8418]
### What happened?

When having an invalid path finding train schedule.
Path items are not visible on map even if they match a PR.

![image](https://github.com/user-attachments/assets/279e78b0-f942-49ed-90ac-195c811b0c85)

> [!NOTE]
> I tried with path items using `operational_point` variant. But it might be the case with other variant such as `track_offset`, `trigram`, `uic`...

### What did you expect to happen?

I should see path items on the map.

### How can we reproduce it (as minimally and precisely as possible)?

1. Import [train_schedules.1.json](https://github.com/user-attachments/files/17246674/train_schedules.1.json)
2. Edit the "nope" train and go to the "Route" tab
3. We can see the list of path items but nothing on the map 

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

0f97f32f7509cc9722a1a33bec7462ee22009e82

**Comment by RomainValls** [comment]
Postponed, will be fixed with this ticket : https://github.com/osrd-project/osrd-confidential/issues/632

**Comment by axrolld** [comment]
> Postponed, will be fixed with this ticket : https://github.com/osrd-project/osrd-confidential/issues/632

I disagree with this. That bug isn't about operational points that aren't found. All points exist but they're not displayed because no path is found.

If i try to trigger this situation manually the points are visible in the map:

![Image](https://github.com/user-attachments/assets/4101fd0e-b2f2-4105-8813-c401d748d7d4)

But with an imported train it doesn't work
