### ISSUE TITLE
front: cannot search the scenario

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#8612]
### What happened?

I try to filter the scenario with the name or the label and no scenario is displayed

### What did you expect to happen?

I should see the correct scenario

### How can we reproduce it (as minimally and precisely as possible)?

1. Navigate to a study with several scenari
2. Try to filter the scenari with its name or label

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

1482e8c

**Comment by Maymanaf** [comment]
The issue remains unresolved

**Comment by EthanPERRUZZA** [comment]
I investigated the bug and found that it is not related to the frontend. The request made by the frontend is correct; however, the `editoast` API returns an empty array, which results in the frontend displaying no data.

The issue lies within the `scenario` object in the endpoint. This object pulls data from the `search_scenario` table, which is currently empty. Since the SQL query performs an INNER JOIN between this table and the `scenario` table, the query result is always empty. This happens because there is no data in `search_scenario` for the query to retrieve.

I couldn't determine why the search_scenario table is not populated, but I’ll consult someone for assistance on Monday.

**Comment by clarani** [comment]
Validated ✅
