### ISSUE TITLE
User and group management CLI

### ISSUE THREAD

**Issue by leovalais** [OpenRailAssociation/osrd#8754]
Part of #8749

### Description and goal

Implement a CLI to manage users and roles.

- [ ] ~~`editoast subject info SUBJECT`~~
- [ ] ~~`editoast subject delete --force SUBJECT`~~
- [x] `editoast group create NAME`
- [ ] ~~`editoast group rename SUBJECT_ID NAME`~~
- [x] `editoast user list` and `editoast user list --without-group`
- [x] `editoast user add IDENTITY [NAME]`
- [x] `editoast group list`
- [x] `editoast group include GROUP_SUBJECT_ID [USER_SUBJECT*]`
- [ ] ~~`editoast group include --interactive` # list users with no group, can interactively add to a group or skip~~
- [x] `editoast group exclude GROUP_SUBJECT_ID [USER_SUBJECT*]`

### Acceptance criteria

The CLI is available.

**Comment by leovalais** [comment]
Note: it would be convenient to use something like `fzf` to handle the interactive part (which gives us multi selection for free btw). There's a crate to wrap its usage: https://crates.io/crates/fzf-wrapped

**Comment by flomonster** [comment]
> Note: it would be convenient to use something like `fzf` to handle the interactive part (which gives us multi selection for free btw). There's a crate to wrap its usage: https://crates.io/crates/fzf-wrapped

Why not, let's be fancy.  @woshilapin Are you akay to add this dependency to editoast (this is probably temporary until we have a proper admin interface).

**Comment by woshilapin** [comment]
Yes, and no. I like the concept of adding a fuzzy searcher, but `fzf` is not Rust, which means complexity for the compilation and possibly deployment (some lib has to be installed, or some binary has to be available). That said, we have other qualitative options for fuzzy search, which are Rust native: [`skim`](https://crates.io/crates/skim/) and [`nucleo`](https://crates.io/crates/nucleo). From what I know about them, `skim` has a CLI fully compatible with `fzf` so I would expect something equivalent. That said, [documentation is nonexistent](https://docs.rs/skim/latest/skim/), so it might be hard to use it (and also, no release since a year). `nucleo` is younger, but is developed for and with the helix editor, and documentation exists.
