### ISSUE TITLE
Margin bugs and input row deletion bugs

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#8959]
### What happened?

I.
Margin of `0min/100km` still computes margin

![image](https://github.com/user-attachments/assets/193564e7-524f-45cf-be7f-00c7b54765a4)

II.
No margin defined (input table):
![image](https://github.com/user-attachments/assets/30cea75c-d403-4b98-8cd8-f15bd36f75dd)

But still, some margins are somehow displayed (output table):
![image](https://github.com/user-attachments/assets/43aefef3-c6d2-402b-bd3d-d5993363e9f2)

III.
Input departure time is bugged when try to update an existing value

https://github.com/user-attachments/assets/fdbf2d51-40d1-4ffe-9405-1d462d3c2f47

IV.
Multi selected fields modification is bugged

https://github.com/user-attachments/assets/74c09e44-5942-4329-967c-8b7c26090056

V.
Delete the value of a stopping time field behaves weirdly
(cf. previous video)

### How can we reproduce it (as minimally and precisely as possible)?

1. open input table
2. play with it
3. open output table

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging fbf8e3e

**Comment by Synar** [comment]
Issue II solved in #9375

Edit : One exception is for the departure, where a theoretical margin of 0% seems to be assumed by the sim, despite not being defined in the input table. Is this what we want?

Edit edit: Actually when deleted, the theoretial margin for the departure is autoset to 0%, but values of 0% are then hidden. Since there is still a defined value for the th margin, the other margins are then displayed. I don't know whether this is working as intended or not.
