### ISSUE TITLE
Osrdyne should clean and update kubernetes ressources

### ISSUE THREAD

**Issue by ghost** [OpenRailAssociation/osrd#9369]
Currently, we can have the deployment that end up in inconsistent states, mainly related to upgrading issue not updating the core since it doesn't .

When starting up osrdyne should :
- Cleanup the stale ScaledObjects if the deployment is not required
- Upgrade the deployments charts

In order to retrigger a core deployment at boot properly, we should:
- Select a random string in the Kubernetes Driver at boot
- Set this string in a label of the deployment
- When starting up, the deployment should be upgraded (triggering a reload of the containers) 

(This mechanism is inspired from the `rollme` system that is sometimes used in charts)

**Comment by flomonster** [comment]
Is it necessary to clean and update k8s resources every time osrdyne starts? A more precise requirement would be that when osrdyne starts up, it should clean up core pods running on a different version.

Instead of using a random string generated at startup, it could use the OSRD_DESCRIBE environment variable. Note that this doesn't work for the dev environment.

**Comment by ghost** [comment]
(Tested on dev cluster directly with manual deployment)
